[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build --configuration production"
  publish = "frontend/dist/pizzaflow-frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
